### ISSUE TITLE
How to put attachment into document

### ISSUE THREAD

**Issue by lambda-knight** [couchrest/couchrest#138]
Hello,
I'm trying to put an attachment into the existing document. 
My code is as follows:

```ruby
require 'couchrest'
conf.echo = false
db = CouchRest.database!("http://admin:admin@127.0.0.1:5984/db-test")
case1 = db.save_doc('_id' => 'case1', 'test-name' => 'bmp test')
case1 = db.get('case1')
file1 = IO.read('../data/test.bmp')
db.put_attachment(case1,"test",file1 , :content_type => "image/bmp")
```
The case1 document is as follows:

```json
{
  "_id": "case1",
  "_rev": "19-d073249b4be05d0c00940b9a0dad3830",
  "test-name": "bmp test",
  "_attachments": {
    "test": {
      "content_type": "text/plain",
      "revpos": 19,
      "digest": "md5-Sf9Zgbi3FmNuVS2t+7xfpg==",
      "length": 787510,
      "stub": true
    }
  }
}
```
The content-type should be 'image/bmp', however it is 'text/plain'.
Then, I tried to fetch the attachment, but it returns 404 error.

```ruby
data = db.fetch_attachment(case1, "test")
CouchRest::NotFound: 404 Not Found
	from /var/lib/gems/2.3.0/gems/couchrest-2.0.1/lib/couchrest/connection.rb:228:in `raise_response_error'
	from /var/lib/gems/2.3.0/gems/couchrest-2.0.1/lib/couchrest/connection.rb:183:in `handle_response_code'
	from /var/lib/gems/2.3.0/gems/couchrest-2.0.1/lib/couchrest/connection.rb:172:in `send_and_parse_response'
	from /var/lib/gems/2.3.0/gems/couchrest-2.0.1/lib/couchrest/connection.rb:157:in `execute'
	from /var/lib/gems/2.3.0/gems/couchrest-2.0.1/lib/couchrest/connection.rb:67:in `get'
	from /var/lib/gems/2.3.0/gems/couchrest-2.0.1/lib/couchrest/database.rb:336:in `fetch_attachment'
	from (irb):18
	from /usr/bin/irb:11:in `<main>'
```
Is my code is wrong ? Please let me know how I can put/fetch attachments.

Thanks,

**Comment by omensinger** [comment]
You need to provide the document to "fetch_attachment", not just its id. See also https://stackoverflow.com/questions/7606838/standalone-attachments-using-couchrest
